### ISSUE TITLE
Uncaught Error: Call to a member function bindValue()

### ISSUE THREAD

**Issue by philippetheis** [ellite/Wallos#68]
I have tried to install Wallos as per the instructions "Baremetal" on my Webserver and Local Webserver. On both i get the same error message.

```
Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: enabled in ../includes/getdbkeys.php on line 20

Fatal error: Uncaught Error: Call to a member function bindValue() on bool in ../includes/getdbkeys.php:21 Stack trace: #0 ../index.php(3): require_once() #1 {main} thrown in ../includes/getdbkeys.php on line 21
```

Does someone know what is the issue? Dependencies like Imagick are installed, PHP is running on version 7.4.33

Thanks

**Comment by ellite** [comment]
Hi.
Did you run the migration?

3. Run http://domain.example/endpoints/db/migrate.php on your browser

**Comment by philippetheis** [comment]
Hi and thanks for your fast response!

yes I did but also getting an error:

```
Warning: Uncaught ErrorException: require_once(includes/connect_endpoint_crontabs.php): failed to open stream: No such file or directory in ../endpoints/db/migrate.php:10 Stack trace: #0 ../endpoints/db/migrate.php(10): errorHandler(2, 'require_once(in...', '/..', 10, Array) #1 ../endpoints/db/migrate.php(10): require_once() #2 {main} thrown in ../endpoints/db/migrate.php on line 10

Fatal error: main(): Failed opening required 'includes/connect_endpoint_crontabs.php' (include_path='.:/Applications/MAMP/bin/php/php7.4.33/lib/php') in ../endpoints/db/migrate.php on line 10
```

**Comment by ellite** [comment]
Strange, error inside the try. 
I haven't tested php7 with the migrate script. 
Can you please switch line 10 with line 12 on the migrate.php and try again?

**Comment by philippetheis** [comment]
with changing line 10 with 12 the migration works!

```
Migration ../../migrations/000002.php completed successfully. Migration ../../migrations/000003.php completed successfully. Migration ../../migrations/000004.php completed successfully.
```

Thanks so far!

**Comment by ellite** [comment]
Awesome. Hopefully everything works now.
Please let me know.
